export const TEST_LIST = [
  {
    id: 1,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    part_number: 4,
    question_number: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 2,
    title: "C18 IELTS reading test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-reading-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 3,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 4,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 5,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 6,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 7,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
  {
    id: 8,
    title: "C18 IELTS listening test 1",
    label: "Bộ đề thi: IELTS C18 Full Test 1",
    time: 40,
    number_part: 4,
    number_questions: 40,
    href: "/tests/c18-ielts-listening-test-1",
    hastags: ["#ielt", "#listening"],
  },
];
